spring:
  application:
    name: spring-cloud-consumer
    
server:
  port: 9001
  register:
    port1: 8000
    port2: 8001
    port3: 8002
    
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.register.port1}/eureka/
      
hystrix:
  threadpool:
    hello:
      coreSize: 20
  command:
    hello:
      circuitBreaker:
        requestVolumeThreshold: 20
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 1000

feign:
  hystrix:
    enabled: true

spring-cloud-producer:
  ribbon:
    #NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    ConnectTimeout: 1000 # 请求连接的超时时间
    ReadTimeout: 1000 # 请求处理的超时时间
    MaxTotalHttpConnections: 500 # 最大总连接数
    MaxConnectionsPerHost: 100 # 单机连接最大数目
    # 重试相关
    MaxAutoRetries: 0 # 对当前实例的重试次数
    MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
    OkToRetryOnAllOperations: false # 对所有操作请求都进行重试    
    
management:
   endpoints:
      web:
         exposure:
            include: hystrix.stream